apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-leader-election-custom-demo
data: { }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-leader-election-custom-demo
  labels:
    app: k8s-leader-election-custom-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-leader-election-custom-demo
  template:
    metadata:
      labels:
        app: k8s-leader-election-custom-demo
    spec:
      serviceAccountName: leader-election-sa
      containers:
        - name: k8s-leader-election-custom-demo
          image: mafeidev/k8s-leader-election-custom-demo:1.0.4
          imagePullPolicy: Always
          #          env:
          #            - name: JAVA_OPTS
          #              value: ""
          ports:
            - containerPort: 3399


---
kind: Service
apiVersion: v1
metadata:
  name: k8s-leader-election-custom-demo
spec:
  type: ClusterIP
  selector:
    app: k8s-leader-election-custom-demo
  ports:
    - port: 8080
      targetPort: 8080
