apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-leader-election-custom-demo
  namespace: default
data: { }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: k8s-leader-election-custom-demo
  name: k8s-leader-election-custom-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-leader-election-custom-demo
  strategy: { }
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: k8s-leader-election-custom-demo
    spec:
      containers:
        - image: mafeidev/k8s-leader-election-custom-demo:1.0.7
          imagePullPolicy: Always
          name: k8s-leader-election-custom-demo
          ports:
            - containerPort: 8080
          resources: { }
status: { }

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: leader
  namespace: default
  labels:
    app: k8s-leader-election-custom-demo
    group: org.springframework.cloud
rules:
  - apiGroups: [ "" ]
    resources: [ "configmaps","pods","endpoints"]
    verbs: [ "get","update","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: k8s-leader-election-custom-demo
    group: org.springframework.cloud
  name: leader
roleRef:
  apiGroup: ""
  kind: Role
  name: leader
subjects:
  - kind: ServiceAccount
    name: default
    apiGroup: ""
    namespace: default