apiVersion: v1
kind: ServiceAccount
metadata:
  name: leader-election-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: leader-election-role
  namespace: default
rules:
  - apiGroups: [ "" ]
    resources: [ "configmaps" ]
    verbs: [ "get", "list", "update" ]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: leader-election-role-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: leader-election-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: leader-election-role
  apiGroup: rbac.authorization.k8s.io
